CREATE OR REPLACE ROW ACCESS POLICY doping_filter
    AS (rider varchar) RETURNS BOOLEAN ->
      CASE
        WHEN current_user() IN ('DEMO_SNOWFLAKE_USER@POSIT.CO') THEN rider NOT IN (
            -- This list was generated by asking Claude for a list of known doping cyclists
            'Armstrong Lance',
            'Landis Floyd',
            'Hamilton Tyler',
            'Ullrich Jan',
            'Pantani Marco',
            'Contador Alberto',
            'Valverde Alejandro',
            'Vinokourov Alexandre',
            'Basso Ivan',
            'Rasmussen Michael',
            'Schleck Frank',
            'Kreuziger Roman',
            'Rebellin Davide',
            'Di Luca Danilo',
            'Ricco Riccardo',
            'Petacchi Alessandro',
            'Scarponi Michele',
            'Sanchez Samuel',
            'Cobo Juan Jose',
            'Horner Chris',
            'Mosquera Ezequiel',
            'Piepoli Leonardo',
            'Kohl Bernhard',
            'Sella Emanuele',
            'Jaksche Jorg',
            'Zabel Erik',
            'Millar David',
            'Boonen Tom',
            'Dekker Thomas',
            'Rabon Dane',
            'Devolder Stijn'
          )
        ELSE true
      END;

ALTER TABLE STAGES ADD ROW ACCESS POLICY doping_filter ON (RIDER);